package com.botcab.matching;

import com.botcab.driver.DriverService;
import com.botcab.ride.Ride;
import com.botcab.ride.RideService;
import com.botcab.ride.RideStatus;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.messaging.simp.SimpMessagingTemplate;

import java.math.BigDecimal;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyDouble;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class OfferServiceTest {

    @Mock
    MatchingService matching;

    @Mock
    DriverService drivers;

    @Mock
    RideService rides;

    @Mock
    SimpMessagingTemplate messaging;

    OfferService offers;

    @BeforeEach
    void setUp() {
        offers = new OfferService(matching, drivers, rides, messaging);
    }

    @Test
    void requestMatchesAndPushesOfferToDriverTopic() {
        Ride ride = requestedRide(10L);
        when(matching.match(eq(11.55), eq(104.92), eq(Set.of())))
                .thenReturn(new MatchResult(2L, 0.4, 1.0));

        OfferMessage msg = offers.requestForRide(ride);

        assertEquals(10L, msg.rideId());
        assertEquals(2L, msg.driverId());
        assertEquals(OfferStatus.PENDING, msg.status());
        assertEquals("offer", msg.note());
        verify(messaging).convertAndSendToUser(eq("driver:2"), eq("/queue/offers"), any(OfferMessage.class));
        verify(messaging).convertAndSend(eq("/topic/rides/10"), any(OfferMessage.class));
    }

    @Test
    void acceptAssignsRideAndKeepsLocationForLiveTracking() {
        Ride ride = requestedRide(5L);
        when(matching.match(anyDouble(), anyDouble(), any()))
                .thenReturn(new MatchResult(1L, 0.1, 1.0));
        when(rides.assignDriver(5L, 1L)).thenReturn(ride);
        OfferMessage pending = offers.requestForRide(ride);

        OfferMessage accepted = offers.accept(pending.offerId(), 1L);

        assertEquals(OfferStatus.ACCEPTED, accepted.status());
        verify(rides).assignDriver(5L, 1L);
        verify(drivers, never()).clearLiveLocation(anyLong());
        verify(drivers, never()).releaseOffer(anyLong());
    }

    @Test
    void rejectReleasesAndOffersNextDriver() {
        Ride ride = requestedRide(7L);
        when(matching.match(eq(11.55), eq(104.92), eq(Set.of())))
                .thenReturn(new MatchResult(1L, 0.1, 1.0));
        when(matching.match(eq(11.55), eq(104.92), eq(Set.of(1L))))
                .thenReturn(new MatchResult(3L, 0.5, 1.0));

        OfferMessage first = offers.requestForRide(ride);
        OfferMessage second = offers.reject(first.offerId(), 1L);

        assertEquals(3L, second.driverId());
        assertEquals(7L, second.rideId());
        assertEquals(OfferStatus.PENDING, second.status());
        verify(drivers).releaseOffer(1L);
        verify(messaging, org.mockito.Mockito.atLeastOnce())
                .convertAndSendToUser(eq("driver:3"), eq("/queue/offers"), any(OfferMessage.class));
    }

    private static Ride requestedRide(long id) {
        Ride ride = new Ride(
                1L,
                BigDecimal.valueOf(11.55),
                BigDecimal.valueOf(104.92),
                BigDecimal.valueOf(11.56),
                BigDecimal.valueOf(104.93));
        // id is generated by JPA — set via reflection for unit tests
        try {
            var field = Ride.class.getDeclaredField("id");
            field.setAccessible(true);
            field.set(ride, id);
        } catch (ReflectiveOperationException e) {
            throw new IllegalStateException(e);
        }
        assertEquals(RideStatus.REQUESTED, ride.getStatus());
        return ride;
    }
}
